version: '3.8'

services:
  # ─── Bases de Datos ───────────────────────────────────────────
  db-auth:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vitalpet_auth
    ports:
      - "3306:3306"

  db-users:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vitalpet_users
    ports:
      - "3307:3306"

  db-pets:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vitalpet_pets
    ports:
      - "3308:3306"

  db-clinical-history:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vitalpet_clinical
    ports:
      - "3309:3306"

  db-appointments:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vitalpet_appointments
    ports:
      - "3310:3306"

  db-staff:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vitalpet_staff
    ports:
      - "3311:3306"

  db-payments:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vitalpet_payments
    ports:
      - "3312:3306"

  db-adoptions:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vitalpet_adoptions
    ports:
      - "3313:3306"

  db-notifications:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vitalpet_notifications
    ports:
      - "3314:3306"

  db-branches:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vitalpet_branches
    ports:
      - "3315:3306"
