<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.vitalpet</groupId>
    <artifactId>vitalpet-connect</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <description>VitalPet Connect - Sistema de Gestión Veterinaria (Multi-module)</description>

    <modules>
        <module>infrastructure/eureka-server</module>
        <module>infrastructure/api-gateway</module>
        <module>ms-auth</module>
        <module>ms-users</module>
        <module>ms-pets</module>
        <module>ms-clinical-history</module>
        <module>ms-appointments</module>
        <module>ms-staff</module>
        <module>ms-payments</module>
        <module>ms-adoptions</module>
        <module>ms-notifications</module>
        <module>ms-branches</module>
    </modules>
</project>
