server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ms-auth
          uri: lb://ms-auth
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2 # Filtro para la url y evitar el Fetch Error

        - id: ms-users
          uri: lb://ms-users
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2 # Filtro para la url y evitar el Fetch Error

        - id: ms-pets
          uri: lb://ms-pets
          predicates:
            - Path=/api/pets/**
          filters:
            - StripPrefix=2 # Filtro para la url y evitar el Fetch Error

        - id: ms-clinical-history
          uri: lb://ms-clinical-history
          predicates:
            - Path=/api/clinical/**
          filters:
            - StripPrefix=2 # Filtro para la url y evitar el Fetch Error

        - id: ms-appointments
          uri: lb://ms-appointments
          predicates:
            - Path=/api/appointments/**
          filters:
            - StripPrefix=2 # Filtro para la url y evitar el Fetch Error

        - id: ms-staff
          uri: lb://ms-staff
          predicates:
            - Path=/api/staff/**
          filters:
            - StripPrefix=2 # Filtro para la url y evitar el Fetch Error

        - id: ms-payments
          uri: lb://ms-payments
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=2 # Filtro para la url y evitar el Fetch Error

        - id: ms-adoptions
          uri: lb://ms-adoptions
          predicates:
            - Path=/api/adoptions/**
          filters:
            - StripPrefix=2 # Filtro para la url y evitar el Fetch Error

        - id: ms-notifications
          uri: lb://ms-notifications
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=2 # Filtro para la url y evitar el Fetch Error

        - id: ms-branches
          uri: lb://ms-branches
          predicates:
            - Path=/api/branches/**
          filters:
            - StripPrefix=2 # Filtro para la url y evitar el Fetch Error
    globalcors:
      cors-configurations:
        '[/**]':
          allowed-origins: "*"
          allowed-headers: "*"
          allowed-methods: "*"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: "01. Auth"
        url: /api/auth/v3/api-docs
      - name: "02. Users"
        url: /api/users/v3/api-docs
      - name: "03. Pets"
        url: /api/pets/v3/api-docs
      - name: "04. Clinical History"
        url: /api/clinical/v3/api-docs
      - name: "05. Appointments"
        url: /api/appointments/v3/api-docs
      - name: "06. Staff"
        url: /api/staff/v3/api-docs
      - name: "07. Payments"
        url: /api/payments/v3/api-docs
      - name: "08. Adoptions"
        url: /api/adoptions/v3/api-docs
      - name: "09. Notifications"
        url: /api/notifications/v3/api-docs
      - name: "10. Branches"
        url: /api/branches/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
